"""all_tables

Revision ID: 142ccb53835a
Revises: 049cc680e4b7
Create Date: 2026-06-18 23:07:10.283449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142ccb53835a'
down_revision: Union[str, Sequence[str], None] = '049cc680e4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias_laborales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('diagnosticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_cie10', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('requiere_junta', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosticos_categoria'), 'diagnosticos', ['categoria'], unique=False)
    op.create_index(op.f('ix_diagnosticos_codigo_cie10'), 'diagnosticos', ['codigo_cie10'], unique=False)
    op.create_table('tipos_licencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('base_legal', sa.String(length=120), nullable=True),
    sa.Column('paga', sa.Boolean(), nullable=False),
    sa.Column('computa_dias', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('empleados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legajo', sa.String(length=40), nullable=False),
    sa.Column('cuil', sa.String(length=13), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_laborales.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_cuil'), 'empleados', ['cuil'], unique=True)
    op.create_index(op.f('ix_empleados_legajo'), 'empleados', ['legajo'], unique=True)
    op.create_table('topes_dias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('tipo_licencia_id', sa.UUID(), nullable=False),
    sa.Column('dias_maximos', sa.Integer(), nullable=False),
    sa.Column('ventana', sa.String(length=32), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.CheckConstraint("ventana IN ('anio-calendario','anio-aniversario','sin-limite')", name='ck_ventana'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_laborales.id'], ),
    sa.ForeignKeyConstraint(['tipo_licencia_id'], ['tipos_licencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'tipo_licencia_id', 'vigente_desde', name='uq_tope_inicio')
    )
    op.create_table('licencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('tipo_licencia_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico_id', sa.UUID(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('dias_otorgados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'VALIDADO', 'RECHAZADO', 'ANULADO', name='estado_licencia'), nullable=False),
    sa.Column('origen', sa.Enum('RRHH', 'MEDICO', name='origen_licencia'), nullable=False),
    sa.Column('observaciones', sa.String(length=2000), nullable=True),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=500), nullable=True),
    sa.Column('certificante', sa.String(length=255), nullable=True),
    sa.Column('matricula_certificante', sa.String(length=40), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('validado_por', sa.UUID(), nullable=True),
    sa.Column('validado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dias_solicitados > 0', name='ck_dias_sol_positivo'),
    sa.CheckConstraint('fecha_hasta >= fecha_desde', name='ck_rango_fechas'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnosticos.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['tipo_licencia_id'], ['tipos_licencia.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjuntos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licencia_id', sa.UUID(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('subido_por', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjuntos')
    op.drop_table('licencias')
    op.drop_table('topes_dias')
    op.drop_index(op.f('ix_empleados_legajo'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_cuil'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_table('tipos_licencia')
    op.drop_index(op.f('ix_diagnosticos_codigo_cie10'), table_name='diagnosticos')
    op.drop_index(op.f('ix_diagnosticos_categoria'), table_name='diagnosticos')
    op.drop_table('diagnosticos')
    op.drop_table('categorias_laborales')
    op.drop_table('areas')
    # ### end Alembic commands ###
