"""add obra_social nro_carnet to empleados

Revision ID: 8cee745dc897
Revises: e614aa488ccc
Create Date: 2026-06-19 20:07:07.481915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cee745dc897'
down_revision: Union[str, Sequence[str], None] = 'e614aa488ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('obra_social', sa.String(length=120), nullable=True))
    op.add_column('empleados', sa.Column('nro_carnet', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'nro_carnet')
    op.drop_column('empleados', 'obra_social')
    # ### end Alembic commands ###
