"""add modo_constatacion to licencias

Revision ID: 958076442bc7
Revises: d8a1e3f5b2c4
Create Date: 2026-06-19 18:47:17.938900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958076442bc7'
down_revision: Union[str, Sequence[str], None] = 'd8a1e3f5b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licencias', sa.Column('modo_constatacion', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licencias', 'modo_constatacion')
    # ### end Alembic commands ###
