"""auditoria table

Revision ID: cf57f12cf1af
Revises: c616894c3934
Create Date: 2026-06-18 20:04:44.260103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf57f12cf1af'
down_revision: Union[str, Sequence[str], None] = 'c616894c3934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=64), nullable=False),
    sa.Column('entidad', sa.String(length=64), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("""
        -- Append-only: app role can INSERT and SELECT but never UPDATE/DELETE.
        REVOKE UPDATE, DELETE ON TABLE auditoria FROM PUBLIC;
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_auditoria_ts_entidad
            ON auditoria (ts DESC, entidad, entidad_id);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    # ### end Alembic commands ###
